### ISSUE TITLE
process merge seems missing in build_kraken.nf

### ISSUE THREAD

**Issue by cschu** [Gibbons-Lab/medi#1]
Hi, the `build_kraken` workflow references a process/workflow named `merge`
```
workflow {
    [...]
    self_classify(library.out, build_kraken_db)
    merge(classify.out.collect(), build_kraken_db)
    build_bracken(merge.out) | add_food_info
}
``` 
However, this identifier is not defined anywhere. As the `build_bracken` command operates on `merge.out`, I also don't assume that this is supposed to be the `Channel.merge` operator.

Thanks,
Christian

**Comment by cdiener** [comment]
My bad, I was reverting a recent change that tried to parallelize the BRACKEN preclassification but it turned out to be too heavy on RAM. Should be fixed now.

**Comment by cschu** [comment]
Cool, thanks. I also assume that the `classify.out.collect()` should actually be `self_classify.out.collect()` ?
