### ISSUE TITLE
May need to add R curl to .yaml

### ISSUE THREAD

**Issue by LesleyHoyles** [Gibbons-Lab/medi#5]
Just installing medi. It requires curl package in R for fread function for nextflow run database.nf command. You may want to add r-curl to the .yaml file.

**Comment by LesleyHoyles** [comment]
Same applies to taxonkit re .yaml file: command could not be found for following command.
taxonkit lineage --data-dir taxdump -i 1 taxids.tsv > raw.txt &&     taxonkit reformat --data-dir taxdump -i 3 raw.txt > lineage.txt &&     taxonkit reformat --data-dir taxdump -t -i 3 raw.txt > lineage_ids.txt

**Comment by LesleyHoyles** [comment]
This may be a non-issue if curl and taxonkit included in r-reutils (I had to install packages individually after setting up basic conda environment to get to work on my system and forgot to conda install conda-forge::r-reutils - apologies if this the case).

**Comment by cdiener** [comment]
Reutils depends on RCurl but best yo add it explicitly as well maybe. Taxonkit was an oversight. I will add those, thanks!
