### ISSUE TITLE
wrong architeuthis version

### ISSUE THREAD

**Issue by atyakhtmpg** [Gibbons-Lab/medi#8]
The referenced version 0.1.2 won't work, it doesn't support some of the used formal parameters. However, the latest (v. 0.2.1) is fine. This should be updated in the README.

**Comment by cdiener** [comment]
Thanks for spotting this! Architeuthis was added to bioconda yesterday so I'll move it to the conda file.

**Comment by cdiener** [comment]
Should be fixed now.
