### ISSUE TITLE
Build database script compilation error

### ISSUE THREAD

**Issue by jjoropezav** [Gibbons-Lab/medi#9]
Hello!

Tried running build_kraken.nf

found this error:

N E X T F L O W  ~  version 23.10.1
Launching `build_kraken.nf` [extravagant_lorenz] DSL2 - revision: 4867f6b59d
ERROR ~ Script compilation error
- file : /scratch/home/joropeza/medi/build_kraken.nf
- cause: Unexpected input: '{' @ line 149, column 10.
   workflow {
            ^

1 error

NOTE: If this is the beginning of a process or workflow, there may be a syntax error in the body, such as a missing or extra comma, for which a more specific error message could not be produced.

 -- Check '.nextflow.log' file for details

---------------------------------------------------------------------------------

Attached is the nextflow log

Thanks for the help
[.nextflow.log](https://github.com/Gibbons-Lab/medi/files/14926909/default.nextflow.log)

**Comment by cdiener** [comment]
Sorry, about that. Should be fixed now.

**Comment by cdiener** [comment]
Should be fixed now.
